# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://octopress.org
title: Octopress
subtitle: A blogging framework for hackers.
author: Brandon Mathis
simple_search: http://google.com/search

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email: brandon@imathis.com

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
port: 4000
permalink: /blog/:year/:month/:day/:title
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
category_title_prefix: "Category: "
markdown: rdiscount
pygments: false

paginate: 10 # Posts per page on the blog index
recent_posts: 5 # Posts in the sidebar Recent Posts section

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Twitter
twitter_user: octopress
twitter_tweet_count: 4
twitter_show_replies: false
twitter_follow_button: true
twitter_show_follower_count: false
twitter_tweet_button: true

# Google Plus
google_plus_one: true
google_plus_one_size: medium

# Pinboard
pinboard_user:
pinboard_count: 4

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name: octopress

# Google Analytics
google_analytics_tracking_id: UA-10876422-2
